### ISSUE TITLE
How did you print the carrier signals on the front panel?

### ISSUE THREAD

**Issue by sofakng** [mecparts/RetroWiFiModem#8]
Thanks for such a great project!  I've ordered the PCB and I'm about to order the parts but I have a question.

How did you print the carrier signal labels (RS, CS, CD, etc) on the gray piece?

Also, if you live in the USA, do you have a single piece of that red screen I could purchase?  Digikey and Mouser are sold out.  :(

**Comment by mecparts** [comment]
The labels are unbelievably low tech. I print them on a piece of inkjet transparency film. I then cut that down to size so that it will fit under the LED opening. Then I attach the trimmed down transparency piece to a length of matte finish, invisible tape and carefully position it in place. A bit of careful work with an x-acto knife and you've got yourself a label that looks like it's part of the panel. If you look closely at the front panel image you can see the edges of the transparency film and the tape, but in practice they both essentially disappear.

I really ought to add that to the readme.

The red filter is out of stock? Yes, I see that it is. And I see that its price has increased by 500%. Ouch! Unfortunately I'm not in the US. DigiKey claims they'll be back in stock in a week; if they're accurate, that's probably your best bet.
